name = "example"
version = "0.1.0"
target = "erlang"

[dependencies]
glasskeys = { path = ".." }
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
storail = ">= 3.0.0 and < 4.0.0"
wisp = ">= 1.0.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.0.0 and < 2.0.0"
nakai = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
given = ">= 6.0.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
