name = "glasskeys"
version = "0.1.0"
description = "Gleam server side verification of Webauthn/FIDO2 credentials"
licences = ["MIT"]
repository = { type = "github", user = "jtdowney", repo = "glasskeys" }

[dependencies]
gbor = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 0.67.1 and < 2.0.0"
kryptos = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.2 and < 2.0.0"
